type AlreadyExistingUserException* = object of CatchableError
